# Generated by Django 5.0.7 on 2024-08-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='create_at',
        ),
    ]
