# Generated by Django 3.2.6 on 2024-07-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240728_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reting',
            new_name='rating',
        ),
    ]
