# Generated by Django 5.0.7 on 2024-08-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pyment_metod',
            field=models.CharField(choices=[('COD', 'Cod'), ('STRIPE', 'Card')], default='COD', max_length=100),
        ),
    ]
