# Generated by Django 5.0.7 on 2024-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_pyment_metod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='createAt',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='pyment_metod',
            field=models.CharField(choices=[('COD', 'Cod'), ('STRIPE', 'Online')], default='COD', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
